services:
    victoire_core.widget_button_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        class: Victoire\Widget\ButtonBundle\Resolver\WidgetButtonContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Button }
    #alias to the entity
    victoire.widget.button:
        class: Victoire\Widget\ButtonBundle\Entity\WidgetButton
    #alias to the form
    victoire.widget.form.button:
        class: Victoire\Widget\ButtonBundle\Form\WidgetButtonType
        tags:
            - { name: form.type , alias: victoire_widget_form_button}

