services:
    victoire_core.twig.widget_button_manager:
        class: Victoire\Widget\ButtonBundle\Widget\Manager\WidgetButtonManager
        arguments: 
            - "@service_container"

    widget_button_manager:
        alias: victoire_core.twig.widget_button_manager
        
    #alias to the entity
    victoire.widget.button:
        class: Victoire\Widget\ButtonBundle\Entity\WidgetButton
    #alias to the form
    victoire.widget.form.button:
        class: Victoire\Widget\ButtonBundle\Form\WidgetButtonType
        tags:
            - { name: form.type , alias: victoire_widget_form_button}
        