services:
    victoire_cms.twig.widget_button_manager:
        class: Victoire\ButtonBundle\Widget\Manager\WidgetButtonManager
        arguments: [@service_container]

    widget_button_manager:
        alias: victoire_cms.twig.widget_button_manager
